<a href="https://colab.research.google.com/github/RajManish8340/100x-school-test/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

In [23]:
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


In [24]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
z = np.zeros((10 , 10))
print("%d bytes" %(z.size * z.itemsize))
print("%d bytes" %(z.nbytes))

800 bytes
800 bytes


In [26]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [27]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [28]:
z  = np.random.randint(2 , size=(3 , 4))
print(z)

[[1 0 1 0]
 [1 0 0 1]
 [1 0 0 1]]


In [29]:
z = np.arange(0,12)
print(z)
print("================================")
r = z.reshape(3 , 4)
print(r)
print("================================")
using_minus_1 = z.reshape(3,-1)
print(using_minus_1)
print("================================")
rr = r.reshape(2 , 2 , 3)
print(rr)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [42]:
z = np.random.randint(25 , size=(5,5))
print(z)
print("=========================")
slice_row = z[3]
print(slice_row)
slice_col = z[: , -1]
print(slice_col)
print("=========================")
top_right_2_by_2 = z[:2 , 3:5]
print(top_right_2_by_2)

[[14  8  7  1 22]
 [18  0 11  0 21]
 [ 8 11 21  2 14]
 [17 17  4  1  4]
 [ 8 21 11 23  3]]
[17 17  4  1  4]
[22 21 14  4  3]
[[ 1 22]
 [ 0 21]]
