<a href="https://colab.research.google.com/github/RajManish8340/100x-school-test/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.__version__
np.show_config()

In [ ]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
z = np.zeros((10 , 10))
print("%d bytes" %(z.size * z.itemsize))
print("%d bytes" %(z.nbytes))

800 bytes
800 bytes


In [ ]:
!python -c "import numpy; numpy.info(numpy.add)"

In [ ]:
z = np.zeros(10)
z[4] = 1
print(z)

In [ ]:
z  = np.random.randint(2 , size=(3 , 4))
print(z)

[[1 0 0 0]
 [1 0 1 1]
 [0 0 1 0]]


In [ ]:
z = np.arange(0,12)
print(z)
print("================================")
r = z.reshape(3 , 4)
print(r)
print("================================")
using_minus_1 = z.reshape(3,-1)
print(using_minus_1)
print("================================")
rr = r.reshape(2 , 2 , 3)
print(rr)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
